"""Initial migration

Revision ID: b2f0c65c64e9
Revises: 
Create Date: 2025-08-19 19:46:29.792904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f0c65c64e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uz', sa.String(length=100), nullable=False),
    sa.Column('ru', sa.String(length=100), nullable=False),
    sa.Column('en', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethnicities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uz_male', sa.String(length=100), nullable=False),
    sa.Column('uz_female', sa.String(length=100), nullable=False),
    sa.Column('ru_male', sa.String(length=100), nullable=False),
    sa.Column('ru_female', sa.String(length=100), nullable=False),
    sa.Column('en_male', sa.String(length=100), nullable=False),
    sa.Column('en_female', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marital_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uz_male', sa.String(length=100), nullable=False),
    sa.Column('uz_female', sa.String(length=100), nullable=False),
    sa.Column('ru_male', sa.String(length=100), nullable=False),
    sa.Column('ru_female', sa.String(length=100), nullable=False),
    sa.Column('en_male', sa.String(length=100), nullable=False),
    sa.Column('en_female', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('religions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uz', sa.String(length=100), nullable=False),
    sa.Column('ru', sa.String(length=100), nullable=False),
    sa.Column('en', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=70), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('accepted_offer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('balance_chances', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('daily_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('TOP_UP', 'BONUS', 'USAGE', 'ADJUST', name='entrykind'), nullable=False),
    sa.Column('source', sa.Enum('Click', 'Payme', 'Uzum', 'Initial', 'Internal', name='source'), nullable=False),
    sa.Column('delta_chances', sa.Integer(), nullable=False),
    sa.Column('amount_sum', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('age_from', sa.Integer(), nullable=True),
    sa.Column('age_to', sa.Integer(), nullable=True),
    sa.Column('height_from', sa.Integer(), nullable=True),
    sa.Column('height_to', sa.Integer(), nullable=True),
    sa.Column('weight_from', sa.Integer(), nullable=True),
    sa.Column('weight_to', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('ethnicity_id', sa.BigInteger(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicities.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('marital_status_id', sa.BigInteger(), nullable=False),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('education', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('religion_id', sa.BigInteger(), nullable=False),
    sa.Column('religious_level', sa.String(length=20), nullable=True),
    sa.Column('ethnicity_id', sa.BigInteger(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=300), nullable=True),
    sa.Column('looking_for', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicities.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marital_status_id'], ['marital_statuses.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewed_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('viewer_id', sa.BigInteger(), nullable=False),
    sa.Column('viewed_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['viewed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'viewed_user_id', name='uq_viewed_profiles')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_profiles')
    op.drop_table('profiles')
    op.drop_table('matchs')
    op.drop_table('filters')
    op.drop_table('balance_entries')
    op.drop_table('users')
    op.drop_table('religions')
    op.drop_table('marital_statuses')
    op.drop_table('ethnicities')
    op.drop_table('cities')
    # ### end Alembic commands ###
